AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 50
    MemorySize: 3000

Parameters:
  OpenAIKey:
    Type: AWS::SSM::Parameter::Value<String>
    Description: OpenAI Key
    Default: OPENAI_API_KEY
    NoEcho: true
  TeleToken:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Telegram Bot Token
    Default: TELE_TOKEN
    NoEcho: true
  AllowedTeleUser:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Telegram User ID that can talk to the bot
    Default: ALLOWED_TELE_USER
    NoEcho: true
  
Resources:
  InferenceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIKey
          TELE_TOKEN: !Ref TeleToken
          ALLOWED_TELE_USER: !Ref AllowedTeleUser
      Events:
        Inference:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /prompt
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./app
      DockerTag: python3.10-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  InferenceApi:
    Description: "API Gateway endpoint URL for Prod stage for Inference function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/prompt/"
  InferenceFunction:
    Description: "Inference Lambda Function ARN"
    Value: !GetAtt InferenceFunction.Arn
  InferenceFunctionIamRole:
    Description: "Implicit IAM Role created for Inference function"
    Value: !GetAtt InferenceFunctionRole.Arn
